### YamlMime:ManagedReference
items:
- uid: System.Activities.Statements.Catch
  id: Catch
  children:
  - System.Activities.Statements.Catch.ExceptionType
  langs:
  - csharp
  name: Catch
  nameWithType: Catch
  fullName: System.Activities.Statements.Catch
  type: Class
  summary: "작업을 해당 예외가 발생 한 후 실행할 포함 <xref uid=&quot;langword_csharp_Try&quot; name=&quot;Try&quot; href=&quot;&quot;> </xref> 블록는 <xref:System.Activities.Statements.TryCatchFinally>활동.</xref:System.Activities.Statements.TryCatchFinally>"
  remarks: "디자이너에 배치 되 면 Catch 활동 디자이너에서 다시 정렬할 수 없습니다.  Catch 활동의 컬렉션을 다시 정렬 하려면 삭제 및 올바른 순서로 다시 추가 하거나 워크플로에 대 한 xaml (코드) 뷰를 사용 합니다."
  syntax:
    content: public abstract class Catch
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Activities.Statements.Catch.ExceptionType
  id: ExceptionType
  parent: System.Activities.Statements.Catch
  langs:
  - csharp
  name: ExceptionType
  nameWithType: Catch.ExceptionType
  fullName: System.Activities.Statements.Catch.ExceptionType
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Statements
  summary: "예외의 유형을 하는 <xref href=&quot;System.Activities.Statements.Catch&quot;> </xref> 블록에서 처리 합니다."
  syntax:
    content: public abstract Type ExceptionType { get; }
    return:
      type: System.Type
      description: "예외 형식입니다."
  overload: System.Activities.Statements.Catch.ExceptionType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Activities.Statements.Catch.ExceptionType
  parent: System.Activities.Statements.Catch
  isExternal: false
  name: ExceptionType
  nameWithType: Catch.ExceptionType
  fullName: System.Activities.Statements.Catch.ExceptionType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Activities.Statements.Catch.ExceptionType*
  parent: System.Activities.Statements.Catch
  isExternal: false
  name: ExceptionType
  nameWithType: Catch.ExceptionType
